### ISSUE TITLE
添加返回顶部按钮

### ISSUE THREAD

**Issue by zhe-he** [jsfront/src#17]
能不能在qq.md文件介绍中，添加返回到顶部？

**Comment by jikeytang** [comment]
github上面不能添加，其实你可以看这个国内的服务器上发布的。
[群规-看云地址－右下角有返回顶部，左边有目录树，非常方便](http://www.kancloud.cn/jikeytang/qq/87646)

**Comment by zhe-he** [comment]
谢谢:smile:

**Comment by S1ngS1ng** [comment]
@zhe-he 其实不需要的。Windows 系统下，按 `Home`/`End` 就可以跳到顶部/底部。macOS 下按 `cmd + 上/下` 就可以跳到顶部/底部
