### ISSUE TITLE
你好,请问你的electron翻译文档为什么和现有的文档不同?

### ISSUE THREAD

**Issue by amhoho** [jsfront/src#26]
你添加的这[两个文档](https://github.com/electron/electron/commit/06a8db8a66c4ccb07bf1c329d4ee6f71ba56a1f5),和现有的electron英文版比起来,多了好多东西,这是为什么?是否根据先前的英文版文档翻译的,还是说那些方法已被废弃了?

**Comment by hiyangguo** [comment]
[Electron 文档  ](https://electronjs.org/) 现已支持中文
